#!/usr/bin/env bash
# Regenerate tool-runner/hexstrike-requirements.lock.txt (GitHub issue #43).
#
# Run this whenever HEXSTRIKE_SHA or the pinned base image in
# tool-runner/runner.Dockerfile changes. It resolves HexStrike's loose
# requirements.txt (minus pwntools/angr, as the Dockerfile strips them) inside
# the SAME Kali base image and Python the runner uses, and writes exact
# versions with sha256 hashes. Review the diff, then build the image:
# `pip install --require-hashes` makes the build fail on any mismatch.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
dockerfile="$root/tool-runner/runner.Dockerfile"
sha="$(sed -n 's/^ARG HEXSTRIKE_SHA=//p' "$dockerfile")"
base="$(sed -n 's/^FROM \(kalilinux[^ ]*\).*/\1/p' "$dockerfile")"
[ -n "$sha" ] && [ -n "$base" ] || { echo "cannot read HEXSTRIKE_SHA / base image from $dockerfile" >&2; exit 1; }

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
cat > "$work/gen.sh" <<INNER
set -e
# Kali's mirror redirector sometimes hands out a broken mirror: retry.
for i in 1 2 3 4 5 6; do
  apt-get update -qq >/dev/null 2>&1
  apt-get install -y -qq --no-install-recommends -o Acquire::Retries=3 \
    python3 python3-venv python3-pip git ca-certificates build-essential python3-dev libffi-dev \
    >/dev/null 2>&1 && break
  echo "apt attempt \$i failed" >&2
done
git clone -q https://github.com/0x4m4/hexstrike-ai.git /src
cd /src && git checkout -q --detach "$sha"
sed -i '/^pwntools/d; /^angr/d' requirements.txt
python3 -m venv /v
/v/bin/pip install -q uv
# --override lets tool-runner/hexstrike-overrides.txt lift versions that
# mitmproxy's own upper bounds would otherwise hold at vulnerable releases.
/v/bin/uv pip compile --generate-hashes --python-version 3.14 --no-header --quiet \
  --override /out/hexstrike-overrides.txt \
  --output-file=/out/hexstrike-requirements.lock.txt requirements.txt
INNER

cp "$root/tool-runner/hexstrike-overrides.txt" "$work/"
docker run --rm -v "$work":/out "$base" bash /out/gen.sh
{
  echo "# Generated by scripts/regenerate_hexstrike_lock.sh (uv pip compile, Python 3.14) for"
  echo "# HexStrike $sha with tool-runner/hexstrike-overrides.txt. Do not edit by hand."
  cat "$work/hexstrike-requirements.lock.txt"
} > "$root/tool-runner/hexstrike-requirements.lock.txt"
echo "wrote tool-runner/hexstrike-requirements.lock.txt ($(wc -l < "$root/tool-runner/hexstrike-requirements.lock.txt") lines) for HexStrike $sha"
